# Site settings
title: YaST
description: powerful installation and configuration tool for Linux
email: yast-devel@opensuse.org
baseurl: ""
url: "https://yast.github.io"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      # use the /blog prefix for the blog posts
      permalink: /blog/:year/:month/:day/:title/

# see http://kramdown.gettalong.org/syntax.html for the format specification
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # no hard line endings, allow reformatting paragraphs
  hard_wrap: false

sass:
  # minify the CSS file
  style: compressed

# pagination config for the blog index page
paginate: 8
paginate_path: "/blog/page:num/"

# generate sitemap.xml and feed.xml automatically by plugins, enable GFM emoji
# and pagination
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# exclude some files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
